<h1>Operations on the ticket</h1>
<p>
	Once a ticket has been selected (or just after it's been created) we can operate on it both via the top and bottom tabs. Top tabs give access to ticket editing and allow the user to see or add attachments and notes.We can also return to the search results page.
</p>
<p>
	<?php print_image("images/help/ticket29.png", false, false); ?>
</p>
<p>
	On the bottom part we can navigate through the tabs that show ticket notes, files, statistics for that ticket, detailed tracking and the active ticket's contacts.
</p>
<p>
	<?php print_image("images/help/ticket35.png", false, false); ?>
</p>
<p>
	On this tab the tickets related to a main ticket can be seen, this means “child” tickets related to the main ticket that's being looked at which acts as a “fathering” ticket. We must remember that when closing the fathering ticket, all of its “child” tickets that are associated will also be closed.
</p>
<p>
	<?php print_image("images/help/ticket30.png", false, false); ?>
</p>
<p>
	Here we can see notes generated by different users, arranged from newest to oldest. From here we can directly add new notes.
</p>
<p>
	<?php print_image("images/help/ticket31.png", false, false); ?>
</p>
<p>
	Just like the Notes part (WorkUnits) we can see the attached files, download them, and upload new ones that we may find suitable.
</p>
<p>
	<?php print_image("images/help/ticket32.png", false, false); ?>
</p>
<p>
	This is the detailed view of a ticket that shows total times, time passed for each status and time dedicated by each person that's involved in a ticket, among other details.
</p>
<p>
	<?php print_image("images/help/ticket34.png", false, false); ?>
</p>
<p>
	In this section we'll be able to see the inventory objects related to a ticket.
</p>
<p>
	<?php print_image("images/help/ticket33.png", false, false); ?>
</p>
<p>
	Here we can see the details on people involved in a ticket.
</p>