<h1>Invoices</h1>
<p>
	Similarly to contracts, they serve the purpose of knowing when there are invoices that have been emitted but not charged, as well as knowing when and where a certain company has been charged. The system is used to manage EMITTED invoices by us, this means, in no case is this an ERP that can calculate treasury cycles, manage lack of payment, or other features common to ERPs. Invoice management, which includes invoice creation in PDF format; is oriented from the point of view of customer, not purveyor, management.
</p>
<p>
	In the Enterprise version there is access control to a company's invoices. The company owner and all the users with a Management (CM) profile have access to them. In the Open Source edition, everyone has access to invoices.
</p>
<p>
	<?php print_image("images/help/company7.png", false, false); ?>
</p>
<p>
	<b>Invoices include a variety of fields. The most important ones are:</b>
	<ul>
		<li><b>Invoice ID:</b> invoice number. It can't be duplicated on another invoice from the system. This system is strictly meant for invoices emitted from our company, therefore it would be impossible to have two invoices with the same ID.</li>
		<li><b>Reference:</b> generally meant to indicate an order number, a shopping order, or similar. Optional</li>
		<li><b>Invoice status:</b> payment pending, paid or cancelled.</li>
		<li><b>Creation date and payment date.</b></li>
		<li><b>Concept:</b> there are five lines with five amounts. For each concept there is an amount. Always in brute costs, without calculating taxes.</li>
		<li><b>Tax:</b> indicate the %, i.e. 21 for 21% taxes.</li>
		<li><b>Currency:</b> EUR is the default currency.</li>
		<li><b>Description:</b> text that will appear on the invoice, generally to clear up data from the order, add more data (for example the account number for payment, etc.).</li>
	</ul>
</p>
<p>
	Once the invoice has been created, we can attach files to it.
</p>
<p>
	<?php print_image("images/help/company8.png", false, false); ?>
</p>
<p>
	An example of its use would be if its an invoice generated by another system and we want to save an image of the original invoice file, here we can attach a file for that.
</p>
<p>
	<?php print_image("images/help/company9.png", false, false); ?>
</p>
<h2>Generating invoice IDs</h2>
<p>
	This utility allows us to automatically generate an ID whenever we create an invoice. For this we'll activate the option 'Enable auto ID' in the CRM configuration, as we can see in the screenshot below:
</p>
<p>
	<?php print_image("images/help/company10.png", false, false); ?>
</p>
<p>
	In the field named “Invoice ID Pattern” a string is save to later be used in generating the IDs. This pattern will contain both a fixed and a variable part. The variable part must be numeric and it will serve as a first element from which a sequence can be calculated. The variable parte will be placed in brackets. The rest will be constant for all invoices.
	Pattern example: 15/[1000]
	</br>
	In this case, the three first invoices that will be generated will be 15/1000, 15/1001 y 15/1002.
	</br>
	Invoice ID generation is only applied to those invoices that are “Sent”.
</p>
<h2>Invoice blocking</h2>
<p>
	An invoice can be blocked -using the lock icon- so that once it's blocked, it can't be modified. It can only be modified by the person who blocked the invoice.
</p>