<?php 

// Integria 2.0 - http://integria.sourceforge.net
// ==================================================
// Copyright (c) 2008 Artica Soluciones Tecnologicas
// Copyright (c) 2008 Esteban Sanchez, estebans@artica.es

// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

require_once ('include/functions_inventories.php');

$filter = array ();
$filter['id_group'] = (int) get_parameter ('user_group_search');
$filter['string'] = (string) get_parameter ('search_string');
$filter['id_contract'] = (int) get_parameter ('search_id_contract');
$filter['id_product'] = (int) get_parameter ('search_id_product');
$filter['id_building'] = (int) get_parameter ('search_id_building');
$filter['ip_address'] = (string) get_parameter ('search_ip_address');
$filter['serial_number'] = (string) get_parameter ('search_serial_number');
$filter['part_number'] = (string) get_parameter ('search_part_number');
$filter['id_company'] = (int) get_parameter ('search_id_company');

$inventories = filter_inventories ($filter);
if ($inventories === false) {
	$inventories = array ();
}

echo '<div style="width: 950px;">';
echo '<h1>'.__('Inventory report').'</h1>';

$generated_str = '<div class="report_info" style="text-align: right; width: 95%;">';
$generated_str .= print_label (__('Generated by').' : ', '', '', true,
	dame_nombre_real ($config['id_user']));
$generated_str .= '<br />';
$generated_str .= print_label (__('Date').' : ', '', '', true, date ('Y-m-d H:i', time ()));
$generated_str .= '</div>';

echo $generated_str;

$output = '<div style="margin-left: 15px; text-align: left; width: 95%;">';

/* Show search criterium */
if ($filter['string'] != '') 
	$output .= print_label (__('Containing').': ', '', '', true,
		'"'.$filter['string'].'"').'<br />';
if ($filter['id_group'] != 0)
	$output .= print_label (__('Group').': ', '', '', true,
		get_db_value ('nombre', 'tgrupo', 'id_grupo', $filter['id_group'])).'<br />';
if ($filter['id_product'] != 0)
	$output .= print_label (__('Product').': ', '', '', true, 
		get_db_value ('name', 'tkb_product', 'id', $filter['id_product'])).'<br />';
if ($filter['id_company'] != 0)
	$output .= print_label (__('Company').': ', '', '', true,
		get_db_value ('name', 'tinventory', 'id', $filter['id_company'])).'<br />';
if ($filter['serial_number'] != '')
	$output .= print_label (__('Serial number').': ', '', '', true,
		$filter['serial_number']).'<br />';
if ($filter['part_number'] != '')
	$output .= print_label (__('Part number').': ', '', '', true,
		$filter['part_number']).'<br />';
if ($filter['ip_address'] != '')
	$output .= print_label (__('IP address').': ', '', '', true, $filter['ip_address']).'<br />';
if ($filter['id_building'] != 0)
	$output .= print_label (__('Building').': ', '', '', true, 
		get_db_value ('name', 'tbuilding', 'id', $filter['id_building'])).'<br />';
if ($filter['id_company'] != 0)
	$output .= print_label (__('Company').': ', '', '', true, 
		get_db_value ('name', 'tcompany', 'id', $filter['id_company'])).'<br />';
if ($filter['id_contract'] != 0)
	$output .= print_label (__('Contract').': ', '', '', true, 
		get_db_value ('name', 'tcontract', 'id', $filter['id_contract'])).'<br />';

$output .= '</div>';
echo '<div class="report_info" style="text-align: left; width: 95%">';
if ($output != '') {
	echo $output;
} else {
	echo __('All inventory');
}
echo '</div>';

// Build object tree
$tree = array ();
$tree_root = array ();
foreach ($inventories as $inventory) {
	$id = $inventory['id'];
	$id_parent = $inventory['id_parent'];

	if (! isset ($tree[$id])) {
		$tree[$id] = array ();
	}

	if ($id_parent > 0) {
		if (! isset ($tree[$id_parent])) {
			$tree[$id_parent] = array ();
		}
		
		array_push ($tree[$id_parent], $id);
	} else {
		array_push ($tree_root, $id);
	}
}

echo '<h3>'.__('Inventory objects statistics').'</h3>';

print_inventory_stats ($inventories);
echo '<div style="clear: both"></div>';

echo '<h3>'.__('Inventory objects list').'</h3>';

echo '<table class="listing" width="95%">';
echo '<tr>';
echo '<th>'.__('ID').'</th>';
echo '<th>'.__('Name').'</th>';
echo '<th>'.__('Active Incidents').'</th>';
echo '<th>'.__('Company').'</th>';
echo '<th>'.__('Building').'</th>';
echo '<th>'.__('Title').'</th>';
echo '</tr>';

$total_inventories = 0;
foreach ($tree_root as $object) {
	print_inventory_object ($object, $inventories, $tree, true, true);
	$total_inventories++;
}

if ($total_inventories == 0) {
	echo '<tr><td colspan="6">'.__('No inventory objects found').'</td></tr>';
}
echo '</table>';
echo '<div style="width: 95%; text-align: left; ">';
include ('general/footer.php');
echo '</div>';
echo '</div>';
?>
